# Generated by Django 6.0.5 on 2026-05-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoticket',
            name='draw_round',
            field=models.IntegerField(default=1),
        ),
    ]
